version: "3"

services:

  frontend:
    build: ./frontend
    container_name: frontend-container

  backend-1:
    build: ./backend
    container_name: backend-container-1

  backend-2:
    build: ./backend
    container_name: backend-container-2

  nginx:
    build: ./nginx
    container_name: nginx-container
    depends_on:
      - frontend
      - backend-1
      - backend-2
    ports:
      - "80:80"
